spring:
  zipkin:
    base-url: http://192.168.28.129:9411
  boot:
    admin:
      client:
        url: http://192.168.28.129:8084

mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: com.xd.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.28.129:8761/eureka/,http://192.168.28.129:8861/eureka,http://192.168.28.129:8961/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"