spring:
  application:
    name: xd-eureka
  zipkin:
  base-url: http://192.168.28.129:9411
  boot:
    admin:
      client:
        url: http://192.168.28.129:8084


server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    #hostname: localhost
    hostname: 192.168.28.129
  client:   #表示是否将自己注册到eureka,因为要构建集群环境，需要将自己注册到集群，所以应该要开启
    register-with-eureka: true
    #表示是否从eureka获取注册的信息，如果是单一节点，不需要同步其他eureka节点，则可以设置为false,但此处为集群，应该设置为true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.28.129:8761/eureka/,http://192.168.28.129:8861/eureka,http://192.168.28.129:8961/eureka/
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #eureka的集群就是多个eureka之间互相注册，一个eureka注册一个eureka而来